version: 2.1

jobs:
  memory_intensive_job:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout

      - run:
          name: Install and Run Stress
          command: |
            sudo apt-get update
            sudo apt-get install -y stress
            stress --vm 1 --vm-bytes 200G --vm-hang 300

      - run:
          name: Completion Message
          command: echo "Memory-intensive test completed."

workflows:
  version: 2
  test_memory_intensive_job:
    jobs:
      - memory_intensive_job
