version: 2.1

jobs:
  memory_intensive_job:
    docker:
      - image: cimg/python:3.9  # Use an appropriate Python Docker image
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install Required Tools
          command: |
            sudo apt-get update && sudo apt-get install -y python3-pip

      - run:
          name: Execute Memory-Intensive Python Script
          command: |
            python3 -c "
              import sys
              
              def allocate_memory_gb(gb):
                  try:
                      print(f'Allocating {gb} GB of memory...')
                      memory = ' ' * (gb * 1024**3)  # Allocate memory
                      print(f'{gb} GB allocated successfully.')
                      input('Press Enter to release memory...')
                  except MemoryError:
                      print('Memory allocation failed!')
                      sys.exit(1)
              
              # Attempt to allocate 200 GB of memory
              allocate_memory_gb(200)
            "

      - run:
          name: Completion Message
          command: echo "Memory-intensive test completed."

workflows:
  version: 2
  test_memory_intensive_job:
    jobs:
      - memory_intensive_job
