version: 2.1

jobs:
  memory_intensive_job:
    machine: true
    steps:
      - checkout

      - run:
          name: Install stress
          command: |
            sudo apt-get update
            sudo apt-get install -y stress

      - run:
          name: Monitor Memory Usage
          command: |
            while true; do
              top
              sleep 10
            done &
            
      - run:
          name: Execute Memory-Intensive Command
          command: |
            # stress --vm 1 --vm-bytes 60G --vm-hang 300

      - run:
          name: Execute I/O Stress Test
          command: |
            stress --io 4000 --timeout 60

      - run:
          name: Completion Message
          command: echo "I/O stress test completed successfully."

workflows:
  version: 2
  memory_test_workflow:
    jobs:
      - memory_intensive_job

