version: 2.1

jobs:
  memory_intensive_job:
    docker:
      - image: cimg/python:3.9  # Choose a suitable Python Docker image
    resource_class: large        # Ensure the job uses a large resource class
    steps:
      - checkout  # Clones your repository
      
      - run:
          name: Install Python Dependencies
          command: |
            pip install --upgrade pip
        
      - run:
          name: Execute Memory-Intensive Python Script
          command: |
            python3 memory_alloc.py 60 5  # Adjust the parameters as needed
        
      - run:
          name: Completion Message
          command: echo "Memory-intensive test completed successfully."

workflows:
  version: 2
  memory_test_workflow:
    jobs:
      - memory_intensive_job
