version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  memory_intensive_job:
    machine: true
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: gradle build -x test

      - run:
          name: Execute Memory-Intensive Task
          command: gradle allocateMemory -PMEMORY_IN_GB=60 -PHOLD_TIME_MINUTES=5

      - run:
          name: Completion Message
          command: echo "Memory-intensive test completed successfully."

workflows:
  version: 2
  memory_test_workflow:
    jobs:
      - memory_intensive_job

